#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jan 25 11:06:53 EET 2022
# SW Build 3118627 on Tue Feb  9 05:13:49 MST 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim RISC_V_TB_behav -key {Behavioral:sim_1:Functional:RISC_V_TB} -tclbatch RISC_V_TB.tcl -log simulate.log"
xsim RISC_V_TB_behav -key {Behavioral:sim_1:Functional:RISC_V_TB} -tclbatch RISC_V_TB.tcl -log simulate.log

